### ISSUE TITLE
Feature request: Add support for "device mode"

### ISSUE THREAD

**Issue by darconeous** [Galvant/gpibusb-firmware#2]
It would be great to have the ability of adapter to go into "device mode", so that you could implement things like fake disk drives and plotters—which could be used directly by certain types of equipment.

**Comment by scasagrande** [comment]
This would probably have to be something implemented in a future version. The problem is that the spec calls for devices on the bus to release control within 200ns of the ATN line being asserted. Usually this is done with dedicated hardware. 

Let me think about it, as I might be able to come up with something on the current hardware version.

**Comment by scasagrande** [comment]
I forgot to post an update here, but as of firmware v5 there is preliminary support for device mode. There might be some bugs in the implementation but it seems to work in my testing where I connected two of my adapters into each other.

**Comment by darconeous** [comment]
Oh neato! I'll have to have a look later.

**Comment by scasagrande** [comment]
You might hate me a little bit, but v5 only works with rev3&4 hardware because of the switch to using the GPIB line driver ICs.

**Comment by darconeous** [comment]
Do'h! :(
